### ISSUE TITLE
Vertical viewport was given unbounded height

### ISSUE THREAD

**Issue by jeffersonatsafe** [PonnamKarthik/FlutterHtmlView#77]
version 0.5.11 (issue did not show up on 0.5.10)

repro code:
HtmlView(data: htmlText)

here's the value of htmlText:
```
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">
<span style=" font-weight:600;">**boldme**</span>
</p> 
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">
<span style=" font-style:italic;">_italicized_</span> 
</p> 
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">     
<span style=" text-decoration: underline;">underlined</span> 
</p> 
<ul style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;">     
<li style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">- bullet1 </li>     
<li style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">- bullet2</li> 
</ul> 
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">     
<span style=" color:#00aaff;">colored</span> 
</p> 
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#00aaff;">
<br/> 
</p> 
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">     
<span style=" font-family:'Arial Black'; font-size:8pt; font-weight:696;">fancy font</span> 
</p> 
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">     
<br/> 
</p> 
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">some 
<a href="http://www.google.com">         
<span style=" text-decoration: underline; color:#0000ff;">hyperlink </span>     
</a> 
</p> 
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">     
<br/> 
</p> 
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">and some weird characters
</p> 
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">&lt;&gt;?';":][}{\| 
</p> 
```

error message:
```
I/flutter (23020): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23020): The following assertion was thrown during performResize():
I/flutter (23020): Vertical viewport was given unbounded height.
I/flutter (23020): Viewports expand in the scrolling direction to fill their container.In this case, a vertical
I/flutter (23020): viewport was given an unlimited amount of vertical space in which to expand. This situation
I/flutter (23020): typically happens when a scrollable widget is nested inside another scrollable widget.
I/flutter (23020): If this widget is always nested in a scrollable widget there is no need to use a viewport because
I/flutter (23020): there will always be enough vertical space for the children. In this case, consider using a Column
I/flutter (23020): instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
I/flutter (23020): the height of the viewport to the sum of the heights of its children.
I/flutter (23020): 
I/flutter (23020): When the exception was thrown, this was the stack:
I/flutter (23020): #0      RenderViewport.performResize.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1129:15)
I/flutter (23020): #1      RenderViewport.performResize (package:flutter/src/rendering/viewport.dart:1182:6)
I/flutter (23020): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:9)
I/flutter (23020): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #19     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter (23020): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #21     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (23020): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #23     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter (23020): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #25     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (23020): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #27     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (23020): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #29     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (23020): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #31     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:479:13)
I/flutter (23020): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #49     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (23020): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #54     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (23020): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #56     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (23020): #57     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (23020): #58     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (23020): #59     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (23020): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #64     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
I/flutter (23020): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (23020): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #80     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2879:14)
I/flutter (23020): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (23020): #82     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (23020): #83     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (23020): #84     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (23020): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (23020): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (23020): #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (23020): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (23020): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (23020): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (23020): #91     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (23020): #92     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (23020): 
I/flutter (23020): The following RenderObject was being processed when the exception was fired:
I/flutter (23020):   RenderViewport#85318 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (23020):   creator: Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#7b335] ← Semantics ← Listener ←
I/flutter (23020):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#e83fa] ←
I/flutter (23020):   _ScrollSemantics-[GlobalKey#4cdae] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
I/flutter (23020):   NotificationListener<ScrollNotification> ← ⋯
I/flutter (23020):   parentData: <none> (can use size)
I/flutter (23020):   constraints: BoxConstraints(0.0<=w<=687.1, 0.0<=h<=Infinity)
I/flutter (23020):   size: MISSING
I/flutter (23020):   axisDirection: down
I/flutter (23020):   crossAxisDirection: right
I/flutter (23020):   offset: ScrollPositionWithSingleContext#0d246(offset: 0.0, range: null..null, viewport: null,
I/flutter (23020):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#bee79,
I/flutter (23020):   ScrollDirection.idle)
I/flutter (23020):   anchor: 0.0
I/flutter (23020): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (23020):   RenderSliverPadding#cbb63 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (23020):     RenderSliverList#ae78a NEEDS-LAYOUT NEEDS-PAINT
```

**Comment by jeffersonatsafe** [comment]
as it turns out, I just needed to bound WebView with a sized container. 
the difference in behaviour between 0.5.10 and 0.5.11 threw me off
